server:
  port: 9084
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    root: info

api:
  gateway:
    base-url: localhost:8082
#  shop:            ##테스트 용도
#    base-url: localhost:9083
#  authentication:
#    base-url: localhost:8081