server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  security:
    oauth2:
      client:
        registration:
          payco:
            client-id: ${PAYCO_CLIENT_ID} #실행시에 넣어줄것
            client-secret: ${PAYCO_CLIENT_SECRET} #실행시에 넣어줄것
            redirect-uri: http://5rora-test.com:8080/login/oauth2/code/payco
            authorization-grant-type: authorization_code
            client-name: payco
        provider:
          payco:
            authorization-uri: https://id.payco.com/oauth2.0/authorize
            token-uri: https://id.payco.com/oauth2.0/token
            user-info-uri: https://apis-payco.krp.toastoven.net/payco/friends/find_member_v2.json
            user-name-attribute: idNo
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # 파일 크기 제한
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379      #각자 쓰고있는 포트에 따라 변경
      database: 1
      username:
      password:

api:
  gateway:
    base-url: localhost:8180
